skip_tags: true
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'
image: Visual Studio 2015

clone_folder: C:\projects\librime-lua

environment:
  BOOST_ROOT: C:\Libraries\libboost
  CL: /Zc:threadSafeInit-

cache:
  - C:\projects\librime\thirdparty.cached -> appveyor.yml
  - C:\projects\librime\thirdparty\bin -> appveyor.yml
  - C:\projects\librime\thirdparty\data -> appveyor.yml
  - C:\projects\librime\thirdparty\include -> appveyor.yml
  - C:\projects\librime\thirdparty\lib -> appveyor.yml
  - C:\Libraries\libboost -> appveyor.yml

init:
  - git --version
  - cmake --version
  - git config --global core.autocrlf true
  - git clone https://github.com/rime/librime.git --depth=1 --recurse-submodules \projects\librime

install:
  - git clone https://github.com/hchunhui/librime-lua.git -b thirdparty --depth=1 thirdparty
  - cd \projects
  - move librime-lua librime\plugins
  - mkdir librime-lua
  - cd librime
  - .\appveyor.install.bat

build_script:
  - cd C:\projects\librime
  - .\build.bat test

after_build:
  - cd C:\projects\librime
  - 7z a rime.zip build\bin build\lib build\include thirdparty\data\opencc
  - move rime.zip ..\librime-lua
  - dir build /s

before_test:
  - cd C:\projects\librime
  - copy /y build\lib\Release\rime.dll build\test\Release

test_script:
  - cd C:\projects\librime\build\test
  - .\Release\rime_test.exe

artifacts:
  - path: rime.zip
    name: Binaries, includes and OpenCC data
